# See https://pre-commit.com for more information
#
# Note: we use `language: system` to make sure that pre-commit uses the same
# dependencies installed by the local project environment (for instance via
# `uv sync --dev --locked`) and not some random version installed in a hidden
# virtualenv. This way running the tools via pre-commit should give the same
# result of running them manually.
#
# Please check README.rst about setting up a development env.

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        language: system
        entry: ruff check --output-format=full
        files: \.py[i]?$
        exclude: tests/test_tstring.py

      - id: ruff-format
        name: ruff format
        language: system
        entry: ruff format --check --diff
        files: \.py[i]?$
        exclude: tests/test_tstring.py

      - id: codespell
        name: codespell
        language: system
        entry: codespell

      - id: mypy
        name: mypy
        language: system
        entry: mypy --pretty --follow-imports=silent
        files: \.py[i]?$
        exclude: tests/test_tstring.py

      - id: cython-lint
        name: cython-lint
        language: system
        entry: cython-lint
        files: \.(pxd|pyx)$

      - id: cargo-fmt
        name: cargo fmt
        language: system
        entry: cargo fmt --all --check
        pass_filenames: false
        files: \.rs$
